<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title></title>
	<base href="http://stephenirl.com/" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="description" content="" />
	<meta name="keywords" content="" />
	<!-- Facebook Open Graph -->
	<meta property="og:title" content="" />
	<meta property="og:description" content="" />
	<meta property="og:image" content="" />
	<meta property="og:type" content="article" />
	<meta property="og:url" content="http://stephenirl.com/" />
	<!-- Facebook Open Graph end -->
		
	<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<script src="js/jquery-1.11.3.min.js" type="text/javascript"></script>
	<script src="js/bootstrap.min.js" type="text/javascript"></script>
	<script src="js/main.js?v=20190120113454" type="text/javascript"></script>

	<link href="css/font-awesome/font-awesome.min.css?v=4.7.0" rel="stylesheet" type="text/css" />
	<link href="css/site.css?v=20190120113454" rel="stylesheet" type="text/css" />
	<link href="css/common.css?ts=1571418629" rel="stylesheet" type="text/css" />
	<link href="css/1.css?ts=1571418629" rel="stylesheet" type="text/css" />
	<link rel="shortcut icon" href="/gallery/guitar_pick-ts1458137312.png" type="image/png" />
	<script type="text/javascript">
	window.useTrailingSlashes = true;
</script>
	
	<link href="css/flag-icon-css/css/flag-icon.min.css" rel="stylesheet" type="text/css" />	
	<!--[if lt IE 9]>
	<script src="js/html5shiv.min.js"></script>
	<![endif]-->

	</head>


<body><div class="root"><div class="vbox wb_container" id="wb_header">
	
<div class="wb_cont_inner"></div><div class="wb_cont_outer"></div><div class="wb_cont_bg"></div></div>
<div class="vbox wb_container" id="wb_main">
	
<div class="wb_cont_inner"><div id="wb_element_instance0" class="wb_element wb_element_picture" title=""><a name="Twitch" class="wb_anchor"></a><a href="http://www.twitch.tv/stephenirl" title="Twitch" target="1"><img alt="gallery/twitch" src="gallery_gen/a0c790c59ac92c35c2e111fe2c105699_50x50.png"></a></div><div id="wb_element_instance1" class="wb_element wb_element_picture" title=""><a name="Youtube" class="wb_anchor"></a><a href="https://www.youtube.com/channel/UChMvT_ZBqJ0RK3x5h3axoFw?view_as=subscriber" title="Youtube" target="1"><img alt="gallery/youtube" src="gallery_gen/8b90068d77886c45fd76b4670f70e3f0_50x50.png"></a></div><div id="wb_element_instance2" class="wb_element wb_element_shape"><div class="wb_shp"></div></div><div id="wb_element_instance3" class="wb_element wb_element_picture" title=""><a name="Discord" class="wb_anchor"></a><a href="http://www.discord.gg/stephenirl" title="Discord" target="1"><img alt="gallery/discord" src="gallery_gen/fd9418f4d74902ac56da0a9a25d00124_51x50.png"></a></div><div id="wb_element_instance4" class="wb_element wb_element_picture" title=""><a name="Twitter" class="wb_anchor"></a><a href="https://twitter.com/StephenIRL_" title="Twitter" target="1"><img alt="gallery/twitter-png-file" src="gallery_gen/e56d588461a3bd5218f4aede3f1d4ab8_50x50.png"></a></div><div id="wb_element_instance5" class="wb_element wb_element_picture" title=""><a name="Instagram" class="wb_anchor"></a><a href="https://www.instagram.com/stephen_irl/" title="Instagram" target="1"><img alt="gallery/instagram" src="gallery_gen/4c7769ae5a966934300d2be20e49c643_50x50.png"></a></div><div id="wb_element_instance6" class="wb_element wb_element_picture" title=""><a name="Patreon" class="wb_anchor"></a><a href="https://www.patreon.com/stephenirl" title="Patreon" target="1"><img alt="gallery/logo-patreon-picture-14" src="gallery_gen/56725b4c5c99694dbd0cab720d7d9023_50x50.png"></a></div><div id="wb_element_instance7" class="wb_element" style="width: 100%;">
						<script type="text/javascript">
				$(function() {
					$("#wb_element_instance7").hide();
				});
			</script>
						</div></div><div class="wb_cont_outer"></div><div class="wb_cont_bg"></div></div>
<div class="vbox wb_container" id="wb_footer">
	
<div class="wb_cont_inner" style="height: 80px;"><div id="wb_element_instance8" class="wb_element" style="text-align: center; width: 100%;"><div class="wb_footer"></div><script type="text/javascript">
			$(function() {
				var footer = $(".wb_footer");
				var html = (footer.html() + "").replace(/^\s+|\s+$/g, "");
				if (!html) {
					footer.parent().remove();
					footer = $("#wb_footer, #wb_footer .wb_cont_inner");
					footer.css({height: ""});
				}
			});
			</script></div></div><div class="wb_cont_outer"></div><div class="wb_cont_bg"></div></div><div class="wb_sbg"></div></div></body>
</html>
